Paginacion rrhh
UNPSJB/mef pull request #71
Opened 2024-05-15 23:25 UTC by CarlosIrigoyen

2024-05-22 19:56 UTC, danibarria requested changes

2024-05-22 19:56 UTC, danibarria commented on services/visita.js
> +    console.log(`Número de registros filtrados: ${recordsFiltered}`);
```suggestion
```

2024-05-22 19:56 UTC, danibarria commented on routes/visitas.js
> +    console.log(horariosDisponibles);
```suggestion
```

2024-05-22 19:56 UTC, danibarria commented on services/Untitled-2.js
> + { [Symbol(or)]:
Qué es este archivo?

2024-05-22 19:56 UTC, danibarria commented on services/Untitled-1.js
> +const models = require('../models');
este archivo que significa?

2024-05-22 19:56 UTC, danibarria commented on services/fosil.js
> +    console.log(`Número de registros filtrados: ${recordsFiltered}`);
```suggestion
```

2024-05-22 19:56 UTC, danibarria commented on services/guia.js
> +      .then(persona => {
Esto lo deberiamos pasar a async/await

2024-05-22 19:56 UTC, danibarria commented on services/guia.js
> +            }
```suggestion
            ${
              querySearch
                ? `"WHERE Persona"."identificacion" ILIKE :searchTerm OR EXISTS (SELECT 1 FROM "IdiomaGuia" AS "IG" JOIN "Idiomas" AS "I" ON "IG"."IdiomaId" = "I"."id" WHERE "IG"."GuiumId" = "Guia"."id" AND "I"."nombre" ILIKE :searchTerm)`
                : ''
            }
```

2024-05-22 19:56 UTC, danibarria commented on services/visita.js
> +      const horariosFinales = horariosDisponibles.filter(horario => !horariosOcupados.includes(horario));
no esta mal pero estaria bueno que sea mas facil de leer, algo como

const horariosNoDisponibles = await models.Visita.findAll({ ...
const horariosDisponibles = HORARIOS_DISPONIBLES.filter(horario => !horariosNoDisponibles.includes(horario));

2024-07-14 19:00 UTC, CarlosIrigoyen commented on services/visita.js
> +      const horariosFinales = horariosDisponibles.filter(horario => !horariosOcupados.includes(horario));
dejame pasar esta

2024-07-16 20:35 UTC, merged